// Navbar dropdown children for 专题, generated by scanning markdown
// frontmatter for `series:` — the navbar follows content with zero
// manual edits. Must run from the repo root (all pnpm scripts do).
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

// keep in sync with seriesPlugin.js
const slugify = (name) =>
  name.replace(/[ _]/g, "-").replace(/[:?*|\\/<>]/g, "").toLowerCase();

const walk = (dir, out = []) => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith(".md")) out.push(full);
  }
  return out;
};

// seriesRoot: URL prefix of the locale ("/" for zh, "/en/" for en)
export const seriesChildren = (srcDir, seriesRoot) => {
  const counts = new Map();

  for (const file of walk(join(process.cwd(), "src", srcDir))) {
    const raw = readFileSync(file, "utf8");
    // same article rule as seriesPlugin: `article: false` pages (e.g.
    // encrypted ones) are excluded, otherwise the link would 404
    if (/^article:[ \t]*false\b/m.test(raw)) continue;
    const match = raw.match(/^series:[ \t]*"?([^"\r\n]+)"?/m);
    if (match) counts.set(match[1], (counts.get(match[1]) ?? 0) + 1);
  }

  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([name]) => ({
      text: name,
      icon: "layer-group",
      link: `${seriesRoot}series/${slugify(name)}/`,
    }));
};
